### ISSUE TITLE
2.3.0 incompatible with mediainfo 18.08

### ISSUE THREAD

**Issue by Vascom** [sbraz/pymediainfo#58] opened 2018-09-07 05:24 UTC
Some tests are failed:
https://kojipkgs.fedoraproject.org/work/tasks/8329/29528329/build.log

**Comment by sbraz** [comment] 2018-09-07 10:44
Thanks for the report, the `test_track_details` problem was related to a legacy attribute, I've fixed that.
The unicode problem is a bug that I've reported upstream. There isn't much I can do about it.

**Comment by JeromeMartinez** [comment] 2018-09-07 10:45
@Vascom we'll release a new version of the library soon.

**Comment by Vascom** [comment] 2018-09-07 10:51
So I am not need to rebuild pymediainfo for updated mediainfo 18.08?

**Comment by sbraz** [comment] 2018-09-07 10:51
pymediainfo doesn't link with libmediainfo, it loads the library dynamically.

**Comment by JeromeMartinez** [comment] 2018-09-07 10:52
I suggest to wait for next MediaInfoLib version before rebuilding/updating, as the issue is from MediaInfoLib, in order to have the test succeed.

**Comment by Vascom** [comment] 2018-09-07 10:53
OK.

**Comment by sbraz** [comment] 2018-09-17 10:41
Fixed in https://github.com/MediaArea/MediaInfoLib/commit/6105a8d2e62221ca8ab3450a7b20cfb370f96ce6 (included in v18.08.1).

**Closed by sbraz** 2018-09-17 10:41 UTC

**Comment by dvzrv** [comment] 2018-11-07 18:45
@sbraz can you release a new version with the fix? I am currently maintaining pymediainfo for Arch Linux and this failing test breaks reproducibility.

Thanks! :)

**Comment by sbraz** [comment] 2018-11-07 21:34
@dvzrv this is a libmediainfo issue, what is the issue with pymediainfo? Do you have a link to a bug?

**Comment by dvzrv** [comment] 2018-11-08 08:40
Sorry for necro-bumping this ticket. As you referenced `test_track_details` it seemed to me, as if this was related to the issue I'm currently seeing with libmediainfo 18.08.1 in the test session for the package:

```
============================= test session starts ==============================
platform linux -- Python 3.7.1, pytest-3.9.3, py-1.7.0, pluggy-0.8.0
rootdir: /build/python-pymediainfo/src/python-pymediainfo-2.3.0, inifile:
collected 16 items

tests/test_pymediainfo.py .........F......                               [100%]

=================================== FAILURES ===================================
___________________ MediaInfoLibraryTest.test_track_details ____________________

self = <test_pymediainfo.MediaInfoLibraryTest testMethod=test_track_details>

    def test_track_details(self):
>       self.assertEqual(self.mi.tracks[1].codec, "AVC")
E       AssertionError: None != 'AVC'

tests/test_pymediainfo.py:63: AssertionError
=============================== warnings summary ===============================
pymediainfo/__init__.py:209
  /build/python-pymediainfo/src/python-pymediainfo-2.3.0/pymediainfo/__init__.py:209: DeprecationWarning: invalid escape sequence \S
    lib_version = tuple(int(_) for _ in re.search("^MediaInfoLib - v(\S+)", lib_version).group(1).split("."))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============== 1 failed, 15 passed, 1 warnings in 3.69 seconds ================
```

Maybe it's unrelated. Should I open another ticket?

**Comment by sbraz** [comment] 2018-11-08 08:48
You're right, tests would fail with 18.08.1 but this is only because I was using legacy attributes. I will release a new version later today.
