### ISSUE TITLE
Can not get video bit depth with pymediainfo but mediainfo v20.03 can display bit depth info

### ISSUE THREAD

**Issue by AceCLee** [sbraz/pymediainfo#83] opened 2020-04-05 09:50 UTC
mediainfo v19.09 also can not display video bit depth of the video.

**Comment by sbraz** [comment] 2020-04-05 10:09
Please give me more info: what OS are you running? If you're on OSX or Windows, pymediainfo tries the bundled library first so you need to pass your up-to-date `library_file` to the `parse` method.

**Comment by AceCLee** [comment] 2020-04-06 05:07
> Please give me more info: what OS are you running? If you're on OSX or Windows, pymediainfo tries the bundled library first so you need to pass your up-to-date `library_file` to the `parse` method.

My os is windows. Actually, I install MediaInfo with GUI installer, and the dir of MediaInfo is the same one. Old MediaInfo.dll of v19.09 has been replaced by the new one of v20.03.

**Comment by AceCLee** [comment] 2020-04-06 05:59
I have replaced MediaInfo.dll in pymediainfo dir.
Pymediainfo 4.1 raises error sometime, but 4.0 works fine.
error:
```
  File "C:\Users\Ace\AppData\Local\Programs\Python\Python37\lib\site-packages\pymediainfo\__init__.py", line 321, in parse
    return cls(output, encoding_errors)
  File "C:\Users\Ace\AppData\Local\Programs\Python\Python37\lib\site-packages\pymediainfo\__init__.py", line 151, in __init__
    xml_dom = ET.fromstring(xml.encode("utf-8", encoding_errors))
  File "C:\Users\Ace\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

**Comment by sbraz** [comment] 2020-04-06 07:10
Please upload an example file and show me the exact `parse()` call you're doing. I don't have any problems with the latest version so I'm assuming this is caused by a specific file.

**Comment by AceCLee** [comment] 2020-04-06 15:04
I call `parse` like this `MediaInfo.parse(filepath).to_data()`.

Actually, `xml.etree.ElementTree.ParseError` occurs conditionally.

I have developed a software to transcode video automatically.

When I use multi-thread mode to process video, audio and other media concurrently (each thread needs to call  `MediaInfo.parse(filepath).to_data()` to get media info data), pymediainfo will raise `ParseError` for some media files.
For the media files above, I have tried to rerun my software for several times, every time pymediainfo raises `ParseError`.

But for the same media files, when I disable the multi-thread mode( the software will process video, audio and other media orderly), it works fine.

Maybe different threads call `MediaInfo.parse(filepath).to_data()` concurrently, but different threads should be independent when using pymediainfo.

For multi-thread mode, It seems like to have too many io operations, usage of HDD is very high when using multi-thread mode. It is a possible reason to cause some io errors.

After that, I installed pymediainfo 4.0 with pip, pymediainfo works fine with multi-thread mode for the same media files above.

**Comment by sbraz** [comment] 2020-04-06 15:11
So you're running into https://github.com/sbraz/pymediainfo/issues/76. I will try to release a new version with the fix this week.

**Comment by AceCLee** [comment] 2020-04-06 15:15
Thanks!

**Comment by sbraz** [comment] 2020-04-06 15:17
And I have updated the bundled version of libmediainfo in 0739dda4179ed827ead27a9a1f4d30356895a730 so it will be up-to-date in the next release.

**Comment by AceCLee** [comment] 2020-04-06 15:20
OK. Thanks for your efforts.

**Comment by sbraz** [comment] 2020-04-13 23:09
@AceCLee can you please try the git master version with your threads?

**Comment by AceCLee** [comment] 2020-04-14 10:25
@sbraz It works. Thanks!

**Comment by sbraz** [comment] 2020-04-14 10:27
Thanks, I'll close this as a duplicate of #76.

**Closed by sbraz** 2020-04-14 10:27 UTC
