### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by erikpkn** [sbraz/pymediainfo#76] opened 2020-01-15 15:15 UTC
I'm calling `MediaInfo.parse()` in a thread. That leads (sometimes) to the following exception:

    Traceback (most recent call last):
      File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.7/threading.py", line 865, in run
        self._target(*self._args, **self._kwargs)
      File "/opt/etha/etha-music-player", line 207, in __get_tags
        media_info = MediaInfo.parse(self.play_item_real_format)
      File "/usr/local/lib/python3.7/dist-packages/pymediainfo/__init__.py", line 263, in parse
        lib, lib_version_str, lib_version = cls._get_library(library_file)
      File "/usr/local/lib/python3.7/dist-packages/pymediainfo/__init__.py", line 205, in _get_library
        lib_version_str = re.search(r"^MediaInfoLib - v(\S+)", lib_version_str).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'

That's in the method `_get_library()`.

I suspect it has something to do with that method being a `@staticmethod`, but for me the cause of this exception is hard to pinpoint.

When I use `threading.RLock()` to lock `MediaInfo.parse()`, all is well, but then the advantage of using threads is lost.

Can you look into this?

I'm using `pymediainfo v4.1` with `libmediainfo Version 18.12` on `Raspbian Buster` on a Raspbian Pi.

**Comment by sbraz** [comment] 2020-01-15 15:25
Hi, can you provide a simple test script? Otherwise I guess I can just run 100 threads at once and find one that fails.

I'm not 100% sure but I don't think the library itself is thread-safe. I'd have to ask them.

**Comment by sbraz** [comment] 2020-01-15 16:50
OK I can reproduce that, the ctypes handle is the same for all threads and it fails. Let me see if I can fix that.

**Comment by sbraz** [comment] 2020-01-15 17:10
Looks like it doesn't have anything to do with static methods. Just the fact that the library doesn't like being passed an empty handle. Can you please try the `fixversion` branch?

**Comment by sbraz** [comment] 2020-01-15 17:20
Even then, it doesn't always work. The version part doesn't fail any more but the output isn't reliable.
@JeromeMartinez is the library supposed to be thread-safe? My tests show that the output sometimes contains bits of XML and non-XML data :/ as if the memory wasn't properly managed.

**Comment by erikpkn** [comment] 2020-01-15 20:30
Sorry, you beat me to it! Since it was almost done, I've finished the test script anyway. Here it is:

    #!/usr/bin/python3 -u
    
    import sys
    import os
    import threading
    from pprint import *
    from pymediainfo import MediaInfo
    
    def get_mediainfo(file):
        media_info = MediaInfo.parse(file)
        for track in media_info.tracks:
            print(track.track_type)
    
        #pprint(media_info.to_data())
    
    def recurse(dir_file):
        ls = os.listdir(dir_file)
        for entry in ls:
            full_entry = os.path.join(dir_file, entry)
            if os.path.isdir(full_entry):
                recurse(full_entry)
            else:
                if os.path.isfile(full_entry):
                    # get_mediainfo(full_entry)
                    threading.Thread(target=get_mediainfo, args=(full_entry,)).start()
    
    def main():
        for dir_file in sys.argv[1:]:
            recurse(dir_file)
    
    if __name__ == "__main__":
        main()

Just start it with a bunch of files or directories as arguments.

Here's a (part of a) sample output:

    Exception in thread Thread-202:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.7/threading.py", line 865, in run
        self._target(*self._args, **self._kwargs)
      File "/opt/etha/test_pymediainfo.py", line 10, in get_mediainfo
        media_info = MediaInfo.parse(file)
      File "/usr/local/lib/python3.7/dist-packages/pymediainfo/__init__.py", line 263, in parse
        lib, lib_version_str, lib_version = cls._get_library(library_file)
      File "/usr/local/lib/python3.7/dist-packages/pymediainfo/__init__.py", line 205, in _get_library
        lib_version_str = re.search(r"^MediaInfoLib - v(\S+)", lib_version_str).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
    
    General
    AudioGeneral
    
    Audio
    General
    Audio
    General
    General
    General
    AudioImage
    Audio
    
    General
    Audio
    Exception in thread Thread-211:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.7/threading.py", line 865, in run
        self._target(*self._args, **self._kwargs)
      File "/opt/etha/test_pymediainfo.py", line 10, in get_mediainfo
        media_info = MediaInfo.parse(file)
      File "/usr/local/lib/python3.7/dist-packages/pymediainfo/__init__.py", line 263, in parse
        lib, lib_version_str, lib_version = cls._get_library(library_file)
      File "/usr/local/lib/python3.7/dist-packages/pymediainfo/__init__.py", line 205, in _get_library
        lib_version_str = re.search(r"^MediaInfoLib - v(\S+)", lib_version_str).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
    
    General
    GeneralAudioGeneral

I'll get back to you on the `fixversion` branch, but I'm a little busy right now, so this will take a couple of hours.

**Comment by erikpkn** [comment] 2020-01-15 23:55
I've tried the `fixversion` branch, and I've found nothing wrong with it.

The only gibberish I got was when I didn't lock the pprint() after calling `MediaInfo.parse(file).to_data()` (caused by pprint() intertwining (parts of) lines).

I've modified the test script somewhat to account for that:

    #!/usr/bin/python3 -u
    
    import sys
    import os
    import threading
    from pprint import *
    from pymediainfo import MediaInfo
    
    testlock = threading.RLock()
    
    def get_mediainfo(file):
        global testlock
        media_info = MediaInfo.parse(file)
        media_info_dict = media_info.to_data()
        with testlock:
            pprint(media_info_dict)
    
    def recurse(dir_file):
        ls = os.listdir(dir_file)
        for entry in ls:
            full_entry = os.path.join(dir_file, entry)
            if os.path.isdir(full_entry):
                recurse(full_entry)
            else:
                if os.path.isfile(full_entry):
                    # get_mediainfo(full_entry)
                    threading.Thread(target=get_mediainfo, args=(full_entry,)).start()
    
    def main():
        for dir_file in sys.argv[1:]:
            recurse(dir_file)
    
    if __name__ == "__main__":
        main()

Since I won't be (p)printing anything I don't have to use locking anymore.

As far as I'm concerned: you did a great job! Thank you!

**Comment by sbraz** [comment] 2020-01-16 09:41
Try that code, it fails for me after 10 or 100 threads. Your code is probably less likely to collide. If I were you, I'd uses processes instead of threads unless upstream provides a fix.
```py
#!/usr/bin/env python3
import pymediainfo

import threading
import sys


def target():
    pymediainfo.MediaInfo.parse("tests/data/sample.mkv")

if __name__ == "__main__":
    threads = []
    for i in range(int(sys.argv[1])):
        t = threading.Thread(target=target)
        t.start()
        threads.append(t)
        target()
    for t in threads:
        t.join()
```

**Comment by erikpkn** [comment] 2020-01-16 15:41
I ran your code with 100,000 threads and I got no exceptions.

But I ran the code on a Raspberry Pi, and you're probably using a PC.

So I tried it on my PC, and lo and behold: exceptions everywhere:

    Exception in thread Thread-24:
    Traceback (most recent call last):
      File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
        self.run()
      File "/usr/lib64/python3.7/threading.py", line 870, in run
        self._target(*self._args, **self._kwargs)
      File "/home/erik/bin/test_pymediainfo2.py", line 16, in target
        pymediainfo.MediaInfo.parse("/home/erik/temp/02 - Chadwick, George Whitefield - Symphony No. 3 in F major (1893-94) - II. Andante cantabile.flac")
      File "/usr/lib/python3.7/site-packages/pymediainfo/__init__.py", line 322, in parse
        return cls(output, encoding_errors)
      File "/usr/lib/python3.7/site-packages/pymediainfo/__init__.py", line 151, in __init__
        xml_dom = ET.fromstring(xml.encode("utf-8", encoding_errors))
      File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 1315, in XML
        parser.feed(text)
      File "<string>", line None
    xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

The Raspberry Pi doesn't have a lot of computing power, so the number of concurrent running threads with your code was about 25. On the PC it was way higher.

So you may be right about the thread safety of the MediaInfo library. It used to be thread safe in Version 0.7.6.4 ([https://github.com/MediaArea/MediaInfoLib/blob/master/History_DLL.txt](https://github.com/MediaArea/MediaInfoLib/blob/master/History_DLL.txt)), but that was 12 years ago, and a lot has changed since then.

 (On the Raspberry Pi I'm using Version 18.12 of the MediaInfo library, and on my PC Version 19.09.)

**Comment by sbraz** [comment] 2020-01-16 16:55
Got it: it's this line that causes a problem with v19.09:
https://github.com/sbraz/pymediainfo/blob/8fadb8ccfbd8a039b2439db49e5fb475fed47d37/pymediainfo/__init__.py#L313-L314

The options are shared across threads so when one thread resets the options, the other threads inherit the defaults, see Jérôme's answer [here](https://github.com/sbraz/pymediainfo/pull/71#issuecomment-495891121). There isn't much I can do except maybe calling it only when `mediainfo_options` is used and documenting the fact that you can't use `mediainfo_options` when working with threads.

What do you think?

**Comment by erikpkn** [comment] 2020-01-17 12:18
That would be the optimal solution given the fact that you have no control over MediaInfoLib. Not being able to use `mediainfo_options` in threads is only a small price to pay for being able to use pymediainfo.

I've tested the removal of those two lines on my PC with MediaInfo Version 19.09, and now it's running fine.

Thank you for looking into this and finding a workable solution!

**Comment by JeromeMartinez** [comment] 2020-01-17 13:11
> you can't use mediainfo_options when working with threads.

Definitely something I need to work on, when I started MediaInfo I didn't think that it would be used with different options in threads.

The "Reset" option was a method for better handling this issue in a quick manner, but it has side effects :(.
Options could be used with hundreds of threads, but before launching the threads (so no "Reset"...)
I plan to have something more clean, but no ETA.

**Comment by sbraz** [comment] 2020-03-02 13:08
@JeromeMartinez I've noticed that the file's `UniqueID` is broken when threads are used so I can't reliably compare objects, do you think this is easy to fix?
Let's say I start 10 threads: I'll get the following values:
```
9144
91443263541957566077726756191315881283
914432
91
914432635454FA7714671126E0B21A4186ED43
914432635
91443263541957566
914432635419
91443263541957566
914432635419575660777
```
When the actual ID is `91443263541957566077726756191315881283 (0x44CB54FA7714671126E0B21A4186ED43)`.

**Comment by JeromeMartinez** [comment] 2020-03-02 14:52
> @JeromeMartinez I've noticed that the file's UniqueID is broken when threads are used so I can't reliably compare objects, do you think this is easy to fix?

Oops, obvious non thread-safe code in a third party code I used (128-bit integer).
Could you try https://github.com/MediaArea/MediaInfoLib/pull/1218/files?
(not guaranteed to be merged as is, I'll run some tests before merging and may modify the code)

**Comment by sbraz** [comment] 2020-03-03 09:52
@JeromeMartinez more problems I found during my tests, it looks like dates aren't thread-safe either. Look at the following code:
```py
#!/usr/bin/env python3
import threading
import sys

import pymediainfo

def target():
    mi = pymediainfo.MediaInfo.parse("tests/data/sample.mkv")
    for att in ("file_last_modification_date",
            "file_last_modification_date__local",
            "encoded_date"):
        print(att, getattr(mi.tracks[0], att), end=" ")
    print()

if __name__ == "__main__":
    threads = []
    for i in range(int(sys.argv[1])):
        t = threading.Thread(target=target)
        t.start()
        threads.append(t)
    for t in threads:
        t.join()
```

```
pymediainfo $ ./test.py  20
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:42:01 encoded_date UTC 2019-09-18 12:48:45 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 14:48:45 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 14:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
file_last_modification_date UTC 2019-09-18 12:48:45 file_last_modification_date__local 2019-09-18 14:48:45 encoded_date UTC 2019-05-24 10:42:01 
```

**Comment by JeromeMartinez** [comment] 2020-03-03 09:57
>  it looks like dates aren't thread-safe either. 

True! looks like `gmtime()` is not thread-safe, and I am using it. I need to replace it.

**Comment by JeromeMartinez** [comment] 2020-03-03 11:50
>  it looks like dates aren't thread-safe either.

Please test https://github.com/MediaArea/ZenLib/pull/107/files

**Comment by sbraz** [comment] 2020-04-06 19:58
@erikpkn Are you OK with that note? Is it clear and visible enough?
![image](https://user-images.githubusercontent.com/4833332/78599324-409df800-7851-11ea-81fa-bf03458b9a3f.png)

I've added a similar note for the `mediainfo_options` parameter:
```
Do not use this parameter when running the method simultaneously from multiple threads, it will trigger a reset of all options which will cause inconsistencies or failures.
```

**Comment by erikpkn** [comment] 2020-04-13 19:02
Sorry for the late reply...

Thanks for your effort in reslving this issue!

In the text "with different options" (under "Note:") it is not totally clear if you mean mediainfo_options or the parse options alltogether.
Apart from that, it is fine, and you can close this issue!

**Comment by sbraz** [comment] 2020-04-13 19:06
Good catch! I will change it to `different arguments`, I don't think Python refers to them as _options_.

As for `mediainfo_options`, that _argument_ can't be used at all within threads.

**Closed** 2020-04-13 23:08 UTC
