### ISSUE TITLE
NoneType error for duration and other_duration using absolute path

### ISSUE THREAD

**Issue by 123epsilon** [sbraz/pymediainfo#102] opened 2020-12-14 16:29 UTC
Currently using v5.03 via pip installer, I saw that similar issues have been raised recently and I've been encountering this problem for some time. I've already upgraded my installation but that doesn't seem to fix it.

Essentially I am reading mpg files using pymediainfo.MediaInfo.parse()

Passing in the absolute path:
```mediainfo = pymediainfo.MediaInfo.parse(os.path.join(media_path,'{}.mpg'.format(media)))
		mediaduration = None
		framerate = 29.97
		err = False
		for track in mediainfo.tracks:
			if track.track_type == 'General':
					mediaduration = track.other_duration[3]
					framerate = float(track.frame_rate)
```
Results in other_duration and duration attributes of the track to be NoneType:

```
Traceback (most recent call last):
  File "D:\XML\DbXMLParser\parser.py", line 99, in <module>
    mediaduration = track.other_duration[3]
TypeError: 'NoneType' object is not subscriptable
```
Meanwhile if I reference it by changing directories and using the file name alone it throws no error. Is this an error in my usage?

**Comment by sbraz** [comment] 2020-12-14 16:40
Hi,
I took the liberty of fixing the formatting.
The other errors you might have seen happened during the call to `parse()`. In your case, something different is happening: the duration is not detected properly.

Can you please do the following:
* show me the value of `track.to_data()` (just before you attempt to get its duration)?
* check if calling `mediainfo.exe filename` differs from `mediainfo.exe D:\path\to\filename`?

Also, does it happen for all files? If not, can you send a small example file along with a fully functional test script (it can be minimalistic, as long as it allows me to reproduce the issue).

**Comment by 123epsilon** [comment] 2020-12-14 17:15
Track to data results:

`{'track_type': 'General', 'count': '332', 'count_of_stream_of_this_kind': '1', 'kind_of_stream': 'General', 'other_kind_of_stream': ['General'], 'stream_identifier': '0', 'track_id': 1, 'other_track_id': ['1 (0x1)'], 'count_of_video_streams': '1', 'count_of_audio_streams': '1', 'video_format_list': 'MPEG Video', 'video_format_withhint_list': 'MPEG Video', 'codecs_video': 'MPEG Video', 'audio_format_list': 'MPEG Audio', 'audio_format_withhint_list': 'MPEG Audio', 'audio_codecs': 'MPEG Audio', 'complete_name': 'D:\\XML\\GUIPuller\\export\\LXFConvert\\414167.mpg', 'folder_name': 'D:\\XML\\GUIPuller\\export\\LXFConvert', 'file_name_extension': '414167.mpg', 'file_name': '414167', 'file_extension': 'mpg', 'completename_last': 'D:\\XML\\GUIPuller\\export\\LXFConvert\\414217.mpg', 'foldername_last': 'D:\\XML\\GUIPuller\\export\\LXFConvert', 'filenameextension_last': '414217.mpg', 'filename_last': '414217', 'fileextension_last': 'mpg', 'format': 'MPEG-TS', 'other_format': ['MPEG-TS'], 'format_extensions_usually_used': 'ts m2t m2s m4t m4s tmf ts tp trp ty', 'commercial_name': 'MPEG-TS', 'internet_media_type': 'video/MP2T', 'file_size': 2733622800, 'other_file_size': ['2.55 GiB', '3 GiB', '2.5 GiB', '2.55 GiB', '2.546 GiB'], 'overall_bit_rate_mode': 'CBR', 'other_overall_bit_rate_mode': ['Constant'], 'frame_rate': '59.940', 'other_frame_rate': ['59.940 FPS'], 'delay': '0.115815', 'other_delay': ['00:00:00.000'], 'file_creation_date': 'UTC 2020-12-11 17:51:44.321', 'file_creation_date__local': '2020-12-11 11:51:44.321', 'file_last_modification_date': 'UTC 2020-12-11 17:51:45.352', 'file_last_modification_date__local': '2020-12-11 11:51:45.352', 'fileextension_invalid': 'ts m2t m2s m4t m4s tmf ts tp trp ty'}`

This issue does not happen for all files, however, I am working on an industry application and I would not be able to send you a sample file that fails. I understand if that makes it difficult to fix this issue, I mostly just meant to bring it to your attention, I was able to get around it by changing the working directory of my script.

Feel free to close the issue if you'd like, I was just very confused as to why the way the file is referenced would alter the tracks attribute, especially when other attributes were parsed correctly.

**Comment by sbraz** [comment] 2020-12-14 17:22
You haven't answered that:
> check if calling `mediainfo.exe filename` differs from `mediainfo.exe D:\path\to\filename`?

If you can reproduce the issue with MediaInfo itself, it is not a pymediainfo issue.

**Comment by sbraz** [comment] 2020-12-20 14:09
Hi @123epsilon did you try to run the mediainfo programme directly to see if the same issue occurs?

**Comment by sbraz** [comment] 2021-01-14 09:06
I'm closing this, I assume the problem is with MediaInfo itself. Please reply if you want the issue reopened.

**Closed by sbraz** 2021-01-14 09:06 UTC
